import { Theme } from "../Theme"

const root = document.documentElement

const injectObject = (object: any, path: string) => {
  Object.keys(object).forEach(key => {
    const newPath = `${path}-${key}`
    if (typeof object[key] === "object") injectObject(object[key], newPath)
    else root.style.setProperty(newPath, object[key])
  })
}

/** Injects the theme attributed into css as css variables.
 * Variable names are generated by concatenating all property names.
 *
 * @param theme The theme to inject
 * @param prefix Optional prefix which will be added at the start of each css variable.
 */

export const injectThemeIntoCss = (theme: Theme, prefix?: string) => {
  if (prefix) injectObject(theme, "--" + prefix)
  else injectObject(theme, "-")
}
